#!/bin/zsh

code --install-extension aaron-bond.better-comments
code --install-extension ahmadalli.vscode-nginx-conf
code --install-extension alexanderte.dainty-nord-vscode
code --install-extension alexcvzz.vscode-sqlite
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension ardenivanov.svelte-intellisense
code --install-extension bradlc.vscode-tailwindcss
code --install-extension codezombiech.gitignore
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension divanvisagie.nord-native-theme
code --install-extension dnlytras.nord-wave
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension enkia.tokyo-night
code --install-extension formulahendry.auto-rename-tag
code --install-extension golang.go
code --install-extension GrapeCity.gc-excelviewer
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.js-debug-nightly
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension mtxr.sqltools
code --install-extension mtxr.sqltools-driver-sqlite
code --install-extension octref.vetur
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel5-snippets
code --install-extension qinjia.seti-icons
code --install-extension raynigon.nginx-formatter
code --install-extension ritwickdey.live-sass
code --install-extension ritwickdey.LiveServer
code --install-extension ronnidc.nunjucks
code --install-extension rust-lang.rust
code --install-extension sdras.night-owl
code --install-extension serayuzgur.crates
code --install-extension sidthesloth.html5-boilerplate
code --install-extension stylelint.vscode-stylelint
code --install-extension svelte.svelte-vscode
code --install-extension syler.sass-indented
code --install-extension Wscats.vue
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
